sudo: required
services:
  - docker

#prod dockerfile does not allow as to make any tests
before install:
  - docker build -t ineso/nuitdinfo2019 .


after_success: 
  - docker build -t inestouzi/nuitdinfo2019  .
#login to docker CLI in one single login 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push inestouzi/nuitdinfo2019
  