version: '3'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /app/nodes_modules
      - ./:/app
  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_db
    ports:
      - "3308:3306"

